name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test_metadata:
    runs-on: ubuntu-latest
    name: Test this action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        id: test
        uses: hpe-hcss/metadata-action@main
        with:
          account_ids: "657xxxx"
      - name: Print results
        shell: bash
        run: |
          echo random-number ${{ steps.test.outputs.repos }}
          echo random-number ${{ steps.test.outputs.images }}
